data_file:
    file_name: cars
    file_type: json
    file_path: './raw_data'
    orientation: records
    columns:
        - Name
        - Horsepower
        - Weight_in_lbs
        - Origin
        - Year
    schema:
        columns:
            Name:
                - type: str
                - allow_null: False
            Miles_per_Gallon:
                - type: int
                - allow_null: False
            Cylinders:
                - type: int
                - allow_null: False
            Displacement:
                - type: int
                - allow_null: False
            Horsepower:
                - type: int
                - allow_null: False
            Weight_in_lbs:
                - type: int
                - allow_null: False
            Acceleration:
                - type: float
                - allow_null: False
            Year:
                - type: str
                - allow_null: False
            Origin:
                - type: str
                - allow_null: False

functions_params:
    get_unique_number:
        column: Name
    get_average:
        column: Horsepower
    get_top_max:
        group_by: Name
        sort_by: Weight_in_lbs
        top_n: 5
    get_count_by_value:
        column: Origin
    get_count_by_year:
        column: Year

output_file:
    name: cars
    file_type: csv
    file_path: './output'


